### ISSUE TITLE
Consider making Unity assets available on GitHub as well

### ISSUE THREAD

**Issue by philippgitpush** [nerdywoffy/vrchat-obs-controller#7]
Right now, all Unity assets are kept at Gumroad, which requires an email to download them. Having them on GitHub would allow people to download them without using their email or looking for a temporary throwaway email.

![image](https://user-images.githubusercontent.com/53810001/195939831-9f1014fe-fa8c-4fa9-adee-34ac85570879.png)

**Comment by nerdywoffy** [comment]
Hi, sorry for suuuppeerr late reply, i noticed that downloading through gumroad is a bit tedious, but i'm currently looking for integration to VCC as well
